# Generated by Django 3.1.1 on 2022-05-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_description', models.TextField(max_length=100)),
                ('hotel_images', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('emenities', models.ManyToManyField(to='app.Emenities')),
            ],
        ),
    ]
