# Generated by Django 3.1.1 on 2022-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detail',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
