# Generated by Django 3.1.1 on 2022-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220521_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
